<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>docker on 孤独前行</title><link>/categories/docker/</link><description>Recent content in docker on 孤独前行</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><lastBuildDate>Thu, 11 Feb 2021 00:00:00 +0000</lastBuildDate><atom:link href="/categories/docker/index.xml" rel="self" type="application/rss+xml"/><item><title>docker.sock connect</title><link>/post/docker/docker-sock/</link><pubDate>Thu, 11 Feb 2021 00:00:00 +0000</pubDate><guid>/post/docker/docker-sock/</guid><description>目录 任务失败 解决方案 总结 任务失败 远程派发了一个任务启动一个容器，竟然失败了，平时都没有出现过问题。通过日志查看发现问题如下： ==++Got++ permission denied while trying to connect to</description></item><item><title>docker容器PID</title><link>/post/docker/container-pid/</link><pubDate>Wed, 10 Feb 2021 00:00:00 +0000</pubDate><guid>/post/docker/container-pid/</guid><description>查找docker容器的PID 平时操作容器都是通过容器ID直接操作，例如docker exec -it containerID。可我们也知道docker的容器</description></item></channel></rss>